base_images:
  ansible:
    name: "4.19"
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: "4.19"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  cli:
    name: "4.19"
    namespace: ocp
    tag: cli
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.19"
    namespace: ocp
    tag: openstack-installer
  operator-sdk-mto:
    name: operator-sdk-mto
    namespace: origin
    tag: main
  tests-private-postupg:
    name: tests-private
    namespace: ci
    tag: "4.20"
  tests-private-preupg:
    name: tests-private
    namespace: ci
    tag: "4.19"
  tools:
    name: "4.19"
    namespace: ocp
    tag: tools
  upi-installer:
    name: "4.19"
    namespace: ocp
    tag: upi-installer
  verification-tests:
    name: verification-tests
    namespace: ci
    tag: latest
releases:
  latest:
    release:
      architecture: arm64
      channel: candidate
      version: "4.19"
  target:
    candidate:
      architecture: arm64
      product: ocp
      stream: nightly
      version: "4.20"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: aws-ipi-rehearse-arm-f28
  cron: 30 3 * * *
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_TYPE: m6g.xlarge
      CONTROL_PLANE_INSTANCE_TYPE: m6g.xlarge
      OCP_ARCH: arm64
    test:
    - chain: openshift-upgrade-qe-test
    workflow: cucushift-installer-rehearse-aws-ipi-disconnected-private
